import {defineResourcePack} from '@mofli/core';
import {attachment as a0} from './bells.js';
import {attachment as a1} from './blush.js';
import {bow as a2} from './bow.js';
import {attachment as a3} from './bubbles.js';
import {attachment as a4} from './bunny.js';
import {attachment as a5} from './cheek-stars.js';
import {attachment as a6} from './fireflies.js';
import {attachment as a7} from './flower.js';
import {attachment as a8} from './freckles.js';
import {attachment as a9} from './gem.js';
import {attachment as a10} from './halo.js';
import {hat as a11} from './hat.js';
import {attachment as a12} from './horns.js';
import {attachment as a13} from './medal.js';
import {attachment as a14} from './moon.js';
import {attachment as a15} from './pearls.js';
import {attachment as a16} from './petals.js';
import {attachment as a17} from './ribbons.js';
import {attachment as a18} from './scarf.js';
import {attachment as a19} from './sprout.js';
export const parts=[{name:"Twin Bells",attachment:a0},{name:"Peach Blush",attachment:a1},{name:"Clay Bow",attachment:a2},{name:"Floating Bubbles",attachment:a3},{name:"Floppy Ears",attachment:a4},{name:"Star Freckles",attachment:a5},{name:"Firefly Glow",attachment:a6},{name:"Cream Blossom",attachment:a7},{name:"Sesame Freckles",attachment:a8},{name:"Honey Gem",attachment:a9},{name:"Cream Halo",attachment:a10},{name:"Sage Hat",attachment:a11},{name:"Cream Horns",attachment:a12},{name:"Round Charm",attachment:a13},{name:"Moon Mark",attachment:a14},{name:"Pearl Drops",attachment:a15},{name:"Drifting Petals",attachment:a16},{name:"Ribbon Drops",attachment:a17},{name:"Sage Scarf",attachment:a18},{name:"Twin Sprout",attachment:a19}];
export const accessoryPack=defineResourcePack({id:'mofli.accessories',version:1,attachments:parts});
export default accessoryPack;